build:
  environment:
    node:
      version: 16.15.0
  nodes:
    analysis:
      tests:
        override:
          - yarn lint
          - js-scrutinizer-run
  tests:
    before:
      - command: yarn build
        idle_timeout: 10000
